version: "3.7"

services:
  web:
    image: ghcr.io/flexusmark/btc-tracker:latest
    restart: unless-stopped
    init: true
    ports:
      - "4567:5000"
    volumes:
      - "${APP_DATA_DIR}/data:/data"
    environment:
      ELECTRS_HOST: "${APP_ELECTRS_NODE_IP}"
      ELECTRS_PORT: "3000"
      SECRET_KEY: "${APP_SEED}"
      DB_PATH: "/data/btc_tracker.db"
